### ISSUE TITLE
TWRP compiled with different errors. Help is needed.

### ISSUE THREAD

**Issue by Vladislav4KZ** [VladAndroidGamer/android_device_samsung_j2corelte#1]
Last error:
error: hardware/interfaces/wifi/1.0/vts/functional/Android.bp:17:1: "VtsHalWifiV1_0TargetTestUtil" depends on undefined module "VtsHalHidlTargetTestBase"
error: frameworks/av/media/libstagefright/codecs/gsm/dec/Android.bp:1:1: "libstagefright_soft_gsmdec" depends on undefined module "libgsm"
error: frameworks/av/media/libstagefright/codecs/aacenc/Android.bp:113:1: "libstagefright_soft_aacenc" depends on undefined module "libFraunhoferAAC"
error: frameworks/av/media/libstagefright/codecs/hevcdec/Android.bp:1:1: "libstagefright_soft_hevcdec" depends on undefined module "libhevcdec"
error: frameworks/hardware/interfaces/displayservice/1.0/vts/functional/Android.bp:17:1: "VtsFwkDisplayServiceV1_0TargetTest" depends on undefined module "VtsHalHidlTargetTestBase"
error: frameworks/av/media/ndk/Android.bp:34:1: "libmediandk" depends on undefined module "libmedia_jni"
error: frameworks/av/media/ndk/Android.bp:34:1: "libmediandk" depends on undefined module "libskia"
error: frameworks/av/media/ndk/Android.bp:34:1: "libmediandk" depends on undefined module "libandroid"
error: frameworks/av/media/ndk/Android.bp:34:1: "libmediandk" depends on undefined module "libandroid_runtime"
error: frameworks/av/media/libstagefright/http/Android.bp:1:1: "libstagefright_http_support" depends on undefined module "libandroid_runtime"
error: hardware/interfaces/media/omx/1.0/vts/functional/common/Android.bp:17:1: "VtsHalMediaOmxV1_0CommonUtil" depends on undefined module "VtsHalHidlTargetTestBase"
error: frameworks/native/services/inputflinger/tests/Android.bp:3:1: "inputflinger_tests" depends on undefined module "libskia"
error: frameworks/native/services/inputflinger/tests/Android.bp:3:1: "inputflinger_tests" depends on undefined module "libinputservice"
error: frameworks/av/media/libstagefright/Android.bp:7:1: "libstagefright" depends on undefined module "libyuv_static"
error: frameworks/av/media/libstagefright/Android.bp:7:1: "libstagefright" depends on undefined module "libvpx"
error: frameworks/av/media/libstagefright/Android.bp:7:1: "libstagefright" depends on undefined module "libwebm"
error: frameworks/av/media/libstagefright/Android.bp:7:1: "libstagefright" depends on undefined module "libsonivox"
error: frameworks/av/media/libstagefright/Android.bp:7:1: "libstagefright" depends on undefined module "libvorbisidec"
error: frameworks/av/media/libstagefright/codecs/vorbis/dec/Android.bp:1:1: "libstagefright_soft_vorbisdec" depends on undefined module "libvorbisidec"
error: system/hardware/interfaces/wifi/keystore/1.0/vts/functional/Android.bp:17:1: "VtsHalWifiKeystoreV1_0TargetTest" depends on undefined module "VtsHalHidlTargetTestBase"
error: frameworks/av/media/libstagefright/codecs/avcenc/Android.bp:1:1: "libstagefright_soft_avcenc" depends on undefined module "libavcenc"
error: frameworks/av/media/libstagefright/colorconversion/Android.bp:1:1: "libstagefright_color_conversion" depends on undefined module "libyuv_static"
error: frameworks/av/media/libstagefright/codecs/aacdec/Android.bp:1:1: "libstagefright_soft_aacdec" depends on undefined module "libFraunhoferAAC"
error: frameworks/av/media/libstagefright/codecs/mpeg2dec/Android.bp:1:1: "libstagefright_soft_mpeg2dec" depends on undefined module "libmpeg2dec"
error: frameworks/av/media/libstagefright/codecs/avcdec/Android.bp:1:1: "libstagefright_soft_avcdec" depends on undefined module "libavcdec"
error: frameworks/av/media/libstagefright/codecs/on2/dec/Android.bp:1:1: "libstagefright_soft_vpxdec" depends on undefined module "libvpx"
error: frameworks/av/media/libstagefright/codecs/opus/dec/Android.bp:1:1: "libstagefright_soft_opusdec" depends on undefined module "libopus"
error: system/hardware/interfaces/net/netd/1.0/vts/functional/Android.bp:1:1: "VtsHalNetNetdV1_0TargetTest" depends on undefined module "VtsHalHidlTargetTestBase"
error: frameworks/av/drm/mediadrm/plugins/clearkey/Android.bp:17:1: "libdrmclearkeyplugin" depends on undefined module "libjsmn"
error: frameworks/av/media/libstagefright/codecs/on2/enc/Android.bp:1:1: "libstagefright_soft_vpxenc" depends on undefined module "libvpx"

**Comment by Vladislav4KZ** [comment]
The penultimate error: [  2% 293/13706] host Prebuilt: mkboot...LES/mkbootimg_intermediates/mkbootimg)
ninja: build stopped: subcommand failed.
13:10:06 ninja failed with: exit status 1

#### failed to build some targets (02:30 (mm:ss)) ####

**Comment by parthibx24** [comment]
try `make recoveryimage`

**Comment by Vladislav4KZ** [comment]
Problem solved
